### ISSUE TITLE
Is this an experiment or will it be applied upstream?

### ISSUE THREAD

**Issue by thedrow** [google/ghost-kernel#2]
Is it reasonable to ship the functionality as an external kernel module or do we have to upstream the entire set of patches?
If so, will this eventually happen or are we still in the prototyping stage?

We should clarify this in the README file.

**Comment by neelnatu** [comment]
Unfortunately we cannot ship this as a kernel module (the core scheduling code in the kernel requires this). Upstreaming is definitely a goal and to make this easier we open-sourced the code first to motivate use cases outside of Google. It's kind of a chicken and egg but that's where we are at.

We can add something to the README to convey this sentiment. Any suggestions?

**Comment by jackhumphries** [comment]
Hi Omer,

Thanks for doing this. Could you please sign the CLA and then we can merge this? Thanks.

Jack

**Comment by thedrow** [comment]
I did. For some reason, the status is still failing.

**Comment by jackhumphries** [comment]
I triggered a rescan and the CLA check is now passing. Could you please update the commit based on the review comment and then I will merge? Thanks.

**Comment by thedrow** [comment]
There are no review comments as of yet.
