### ISSUE TITLE
Add compile script and documents for aarch.

### ISSUE THREAD

**Issue by GoWest279** [google/ghost-kernel#4]
Hi, 
I made some progress in compiling ghost-kernel for Raspberry pi 4 and Odroid n2 ARM development boards:)
I read the contribution guideline but am not sure whether I could make a pull request to merge aarch support (script/documentation) to the ghost-kernel repo, as the ghost-kernel is originally focusing on the X86 processor.
If Yes, I'm wondering what's the guideline for adding a new architecture? Or, aarch support has been added at the Google backbend? 
Thanks:)
Bests,
John

**Comment by jackhumphries** [comment]
Hi John,

Thanks for offering to do this. Yes, please open a pull request and we'll be happy to take a look.

Jack

**Comment by jackhumphries** [comment]
Hi John,

I will take a look soon! Thanks for your patience.

Jack

**Comment by GoWest279** [comment]
Hi, Jack,
No worries. This is just some peripheral work. Take your time:)
Bests,
Yifei
