### ISSUE TITLE
FAILED: load BTF from vmlinux: No such file or directory make: *** [Makefile:1165: vmlinux] Error 255

### ISSUE THREAD

**Issue by souravpaul8** [google/ghost-kernel#7]
While trying to compile this kernel on a machine running Ubuntu 20.04.4 LTS (GNU/Linux 5.19.0-051900-generic x86_64), I am getting this error. Can you please help with how to resolve this?

Earlier was getting this error: make[1]: *** No rule to make target 'debian/canonical-certs.pem', needed by 'certs/x509_certificate_list'. Stop. make: *** [Makefile:1809: certs]

**Comment by jackhumphries** [comment]
If you don't need code signing, you can fix this by setting `CONFIG_SYSTEM_TRUSTED_KEYS` to an empty string in your `.config` file:
```
CONFIG_SYSTEM_TRUSTED_KEYS=""
```
